#!/bin/bash

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "$BASE/lib/ui"

title "Alfredo Tools - Speed"

title "Alfredo Tools - Salud"

echo
echo "Uso del disco"
separator
df -h /

echo
echo "Memoria"
separator
free -h

ok "Sistema funcionando correctamente"
